[Issue20]: Add in WTFPL
stevemao/left-pad pull request #35
Opened 2016-09-24 14:00 UTC by cht8687

Add in WTFPL licence.

2016-09-24 23:42 UTC, stevemao commented on index.js
> +     * the extent permitted by applicable law. You can redistribute it
Doesn't look like it's aligned properly. Is it intentional?

2016-09-24 23:42 UTC, stevemao requested changes

2016-09-25 00:23 UTC, cht8687 commented on index.js
> +     * the extent permitted by applicable law. You can redistribute it
Directly copy and paste from official doc.

2016-09-25 00:24 UTC, cht8687 commented on index.js
> +     * the extent permitted by applicable law. You can redistribute it
@stevemao  http://www.wtfpl.net/faq/

2016-09-25 00:25 UTC, cht8687 commented on index.js
> +     * the extent permitted by applicable law. You can redistribute it
shall we align it?

2016-09-25 00:40 UTC, merged