added more test cases and grouped them into multiple tests
stevemao/left-pad pull request #36
Opened 2016-09-25 17:09 UTC by zehua

test test test

2016-09-25 17:10 UTC, zehua commented on test.js
> +  //assert.strictEqual(leftPad('foobar', 8, {}), '  foobar', '{} default to space');
These two currently fail. Not sure if we should make them pass by updating the code.

2016-09-26 00:16 UTC, stevemao commented on test.js
> +  //assert.strictEqual(leftPad('foobar', 8, {}), '  foobar', '{} default to space');
```js
String([])
""

String({})
"[object Object]"
```

The second argument should be always a string, even though we are not forcing it here (we using `String()` to convert anything).

2016-09-26 00:53 UTC, zehua commented on test.js
> +  //assert.strictEqual(leftPad('foobar', 8, {}), '  foobar', '{} default to space');
yeah, I know what the current behaviour is. Passing `[]` will result in nothing being padded, and `{}` with `[object Object]` being padded. They don't look right, but I am just not sure what the desired behaviour should be.

I prefer to handle them in a separate PR. We could enable these two tests at that time.

2016-09-26 03:50 UTC, stevemao commented on test.js
> +  //assert.strictEqual(leftPad('foobar', 8, {}), '  foobar', '{} default to space');
@zehua I understand. I don't see a module should handle everything. users should understand the contract. If not, and if it's a problem, they might already have opened an issue with real-life scenarios :) But yeah it's nothing right or wrong here, just a different paradigm I believe 😄

2016-09-26 05:16 UTC, zehua commented
do you want me to remove these two test cases, or leave them commented here?
On Sep 26, 2016 11:50 AM, "Steve Mao" <notifications@github.com> wrote:

> *@stevemao* commented on this pull request.
> ------------------------------
>
> In test.js <https://github.com/stevemao/left-pad/pull/36>:
>
> >    assert.strictEqual(leftPad('foobar', 6), 'foobar');
> +  assert.strictEqual(leftPad('foobar', 5), 'foobar');
> +  assert.strictEqual(leftPad('foobar', -1), 'foobar');
> +  assert.strictEqual(leftPad('foobar', 6, '1'), 'foobar');
> +  assert.strictEqual(leftPad('foobar', 5, '1'), 'foobar');
> +  assert.strictEqual(leftPad('foobar', -1, '1'), 'foobar');
> +  assert.strictEqual(leftPad('foobar', 8, ''), '  foobar');
> +  assert.strictEqual(leftPad('foobar', 8, false), '  foobar', 'false default to space');
> +  //assert.strictEqual(leftPad('foobar', 8, []), '  foobar', '[] default to space');
> +  //assert.strictEqual(leftPad('foobar', 8, {}), '  foobar', '{} default to space');
>
> @zehua <https://github.com/zehua> I understand. I don't see a module
> should handle everything. users should understand the contract. If not, and
> if it's a problem, they might already have opened an issue with real-life
> scenarios :) But yeah it's nothing right or wrong here, just a different
> paradigm I believe 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stevemao/left-pad/pull/36>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AATMGH5RPDBLhZ2xeeGBH0klkd_gx4apks5qt0D4gaJpZM4KF8v_>
> .
>

2016-09-26 10:16 UTC, stevemao requested changes
remove them. I don't think they are valid use-cases. Unless you have strong opinions?

2016-09-26 14:19 UTC, zehua commented
Removed the commented tests. @stevemao

2016-09-26 23:37 UTC, merged